# permissions for end users to edit mongodbusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbuser-editor-role
rules:
- apiGroups:
  - db.w6d.io
  resources:
  - mongodbusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db.w6d.io
  resources:
  - mongodbusers/status
  verbs:
  - get
