apiVersion: db.w6d.io/v1alpha1
kind: MongoDB
metadata:
  name: mongodb-sample
  namespace: default
spec:
  version: "4.4"
  replicas: 1
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
